url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "a collection of thoughts" # the name of your site, e.g. ACME Corp.
#paginate: 8
#paginate_path: "/blog/page:num/"
